// SPDX-FileCopyrightText: Copyright 2025-2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Fixed build-revision constants for the test binary.
//
// The real values are generated by cmake/configure_file from git metadata into
// ${CMAKE_CURRENT_BINARY_DIR}/src/common/scm_rev.cpp.  That generated file is
// not available to the test target (it contains the real rev hash and requires
// the configure step).  This stub provides stable, predictable values so that
// the version-mismatch branch in EmulatorSettingsImpl::Load() behaves
// deterministically in tests.

#include <string>
#include "common/scm_rev.h"

namespace Common {

constexpr char g_version[]         = "0.0.0 TEST";
constexpr bool g_is_release        = false;
constexpr char g_scm_rev[]         = "test_rev_hash_aabbccdd";
constexpr char g_scm_branch[]      = "test-branch";
constexpr char g_scm_desc[]        = "test-desc";
constexpr char g_scm_remote_name[] = "origin";
constexpr char g_scm_remote_url[]  = "https://github.com/test/shadPS4";
constexpr char g_scm_date[]        = "1970-01-01";

const std::string GetRemoteNameFromLink() {
    return "test";
}

} // namespace Common
